snap

diff --git a/astro/astropost b/astro/astropost
--- a/astro/astropost
+++ b/astro/astropost
@@ -1,19 +1,29 @@
 #!/bin/bash
+# Have debug info in /var/log/cups/error_log:
+#! set -x
+
+# This CUPS backend allows you to "print to file".
+
+# It saves the file into a "cache" and posts the file to a "transfer
+# queue" for copying to another machine.
 #
-# This CUPS backend allows you to "print to file". 
 # Modified from:
 #   http://osdir.com/ml/printing.cups.devel/2004-10/msg00007.html
 # which contained snip (c) Kurt Pfeifle, Danka Deutschland GmbH
 # See also: https://community.kde.org/Printing/Developer_Tools
 #
 # Install a printer like this:
-#   chmod a+x <this.file>
-#   sudo cp <this.file> /usr/lib/cups/backend/sdpost
+#   chmod a+x astropost  # this file
+#   sudo cp astropost /usr/lib/cups/backend/astropost
 #   sudo service cups restart
-#   sudo lpadmin -p astrorepo -v sdpost:/tmp/mountaincache -E
-# There are restrictions on what directory can be written to
+#   sudo lpadmin -p astro -v astropost:/tmp/mountain_cache -E
+# There are restrictions on what directory can be written to.
 #
-# If you print to the "astrorepo" printer, you will find the files from
+# Then you can do things like:
+#   lpstat -a  # should see the printer is "accepting requests"
+#   lpr -P astro mandlelbrot.jpg
+#
+# If you print to the "astro" printer, you will find the files from
 # CUPS filtering produced in "/tmp/astro/*".
 #
 #
@@ -34,8 +44,25 @@
 #   /mtncache/20140921/kp4m/2014B-0461/k4k_140921_235746_zri.fits.fz
 #
 
+error() {
+    local logfile="$1"
+    local parent_lineno="$2"
+    local message="$3"
+    local code="${4:-1}"
+    echo "Did not complete! Error near line ${parent_lineno}." >> ${logfile}
 
-export LOG=/tmp/sdpost.log #!!!
+    if [[ -n "$message" ]] ; then
+        echo "${message}; exiting with status ${code}" >> ${logfile}
+    else
+        echo "Exiting with status ${code}" >> ${logfile}
+    fi
+    exit "${code}"
+}
+
+export LOG=/tmp/astropost.log #!!!
+#!trap 'error ${LOG} ${LINENO}' ERR
+#!trap "echo \"$0 completed successfully\" >> ${LOG}" EXIT
+
 JOBID=$1 ;
 USER=$2 ;
 TITLE=$3 ;
@@ -53,14 +80,14 @@ echo "OPTIONS = " ${OPTIONS} >> ${LOG}
 echo "FILE    = " ${FILE}    >> ${LOG} 
 echo "CONTENT_TYPE = " ${CONTENT_TYPE} >> ${LOG} 
 echo "DEVICE_URI   = "  ${DEVICE_URI} >> ${LOG}
-rootDir="${DEVICE_URI#sdpost:}"
+rootDir="${DEVICE_URI#astropost:}"
 echo "rootDir  = " ${rootDir}         >> ${LOG}
 echo "TMPDIR   = " ${TMPDIR}          >> ${LOG}
 #! echo "FILETYPE = " `file $FILE`        >> ${LOG}
 
 # if there are no arguments: print the "I'm here" message for cupsd's probing
 if [ $# -eq 0 ]; then
-echo "direct sdpost \"Unknown\" \"Print any job to file specified in 
+echo "direct astropost \"Unknown\" \"Print any job to file specified in 
 device-URI\""
 exit 0
 fi
@@ -68,12 +95,12 @@ fi
 # in case of wrong number of arguments: print usage hint
 if [ $# -ne 5 -a $# -ne 6 ]; then
 echo ""
-echo "Usage: sdpost job-id user title copies options [file]"
-echo " example for device-URI: 'sdpost:/path/to/targetfile'"
+echo "Usage: astropost job-id user title copies options [file]"
+echo " example for device-URI: 'astropost:/path/to/targetfile'"
 echo "(this writes the printfile to disk at specified path)"
 echo ""
 echo "Install a printqueue with:\n \
-'lpadmin -p <sdpostr-printer-name> -v sdpost:/</path/to/targetfile> -E'"
+'lpadmin -p <astropost-printer-name> -v astropost:/</path/to/targetfile> -E'"
 echo ""
 exit 1
 fi
@@ -86,19 +113,17 @@ TITLE=`echo ${TITLE} | tr [:blank:] _ | tr : _ | tr / _ | tr "\134" _`;
 
 # get file to which the job is "printed" from device URI, so
 # so that you can use this backend multiple times, for various
-# "sdpost" printers...
-#!TARGETFILE=${DEVICE_URI#sdpost:}
-
-### uncomment&modify the following line if you need the JOBTITLE,
-### USERNAME, JOBID, DATE as part of the filename...
-#! TARGETFILE=${USER}-${JOBID}-${DEVICE_URI#sdpost:}-${TITLE}
-#!TARGETFILE=${USER}-${JOBID}-${TITLE}
+# "astropost" printers...
+#! TARGETFILE=${DEVICE_URI#astropost:}
+#! TARGETFILE=${USER}-${JOBID}-${DEVICE_URI#astropost:}-${TITLE}
+#! TARGETFILE=${USER}-${JOBID}-${TITLE}
 TARGETFILE=${TITLE}
+
 # but check "accepting" status first...
 GREPSTRING="not accepting" ;
-if lpstat -a astrorepo | grep "$GREPSTRING" &> /dev/null ; then
-echo "ERROR: printer $TARGETFILE not accepting jobs..."
-exit 1
+if lpstat -a astro | grep "$GREPSTRING" &> /dev/null ; then
+    echo "ERROR: printer $TARGETFILE not accepting jobs..."
+    exit 1
 fi
 
 mkdir -p ${rootDir}
@@ -111,12 +136,20 @@ else
 fi
 
 # now do the job....
-echo "Copying to: "  ${destdir}/${TARGETFILE}  >> ${LOG}
 mkdir -p $destdir
-cat $FILE > ${destdir}/${TARGETFILE}
+fullfname="${destdir}/${TARGETFILE}"
+echo "Copying to: "  ${fullfname}  >> ${LOG}
+cat $FILE > ${fullfname}             # Add posted file to CACHE
 
- 
- 
+#!echo "Calculate checksum" >> ${LOG}
+#!#!md5sum ${fullfname} >>  ${LOG} #!!!
+#!#!md5sum ${fullfname} >>  ${LOG} #!!!
+#!echo "Pushing ${fullfname} to Transfer Queue" >> ${LOG}
+#!#!/home/pothiers/PYTHON_ENV/data-queue/bin/dqcli --push /tmp/foo
+#!#!/tmp/dqcli --help >> ${LOG} #!!!
+#!#do_nothing.sh >> ${LOG} #!!!
+#!echo "Pushed" >> ${LOG}
+
 # we reach this line only if we actually "printed something"
 echo 1>&2
 echo "NOTICE: processed Job ${JOBID} to file ${destdir}/${TARGETFILE}" 1>&2
